import { lazy, Suspense, useState } from 'react';
import type { Binding, ConsoleSnapshot, Project, StartRecord } from '@meteor-flow/contracts';
import { Monitor, Plus, TerminalSquare } from 'lucide-react';
import type { Run } from './api.js';
import { date, Empty, Field, Modal, Submit } from './ui.js';

const TerminalPanel = lazy(() => import('./TerminalPanel.js'));
const modes = { observe: '观察模式', automatic: '自动调度', manual: '手动使用' };
const observations = { idle: '空闲', done: '观测完成', working: '工作中', blocked: '可能需要人工', unknown: '未知' };
export function Agents({ data, project, run, disabled, fresh, pending, csrf, error, terminalId, openTerminal }: { data: ConsoleSnapshot; project: Project; run: Run; disabled: boolean; fresh: boolean; pending: boolean; csrf: string; error?: string; terminalId: string; openTerminal: (id: string) => void }) {
  const [start, setStart] = useState(false);
  const [resolving, setResolving] = useState<StartRecord | null>(null);
  const [action, setAction] = useState<{ binding: Binding; name: string; title: string; description: string } | null>(null);
  const bindings = data.bindings.filter(binding => binding.projectId === project.id);
  const discoveries = data.discoveries.filter(observation => !data.bindings.some(binding => binding.terminalId === observation.terminalId && binding.session === data.settings.session));
  const terminal = bindings.find(binding => binding.id === terminalId);
  const choose = (binding: Binding, name: string, title: string, description: string) => setAction({ binding, name, title, description });
  return <><div className="page-heading"><div><h1>Agent</h1><p className="muted">{project.name} · 不同 Agent 使用独立的真实工作目录与会话。</p></div><button className="primary" disabled={disabled || project.archived || !data.settings.session} onClick={() => setStart(true)}><Plus size={17} />启动 Agent</button></div>
    {!data.health.connected && <p className="banner warning">herdr 当前不可用。请检查所选 session；保留的观测不能作为输入或调度依据。</p>}
    {bindings.length ? <div className="agent-list">{bindings.map(binding => <section key={binding.id} className="agent-row"><div className="heading-row"><div className="agent-title"><Monitor size={20} /><h2>{binding.label}</h2><span className="tag">{binding.type}</span></div><button onClick={() => openTerminal(binding.id)}><TerminalSquare size={16} />观察终端</button></div><div className="agent-states"><span className="tag">{modes[binding.mode]}</span><span>{binding.paused ? '调度已暂停' : '调度未暂停'}</span><span>{binding.confirmed ? '已确认接入' : '尚未确认接入'}</span><span>占用：{data.attempts.some(attempt => attempt.bindingId === binding.id && attempt.occupies) ? '是' : '否'}</span></div><dl className="facts"><dt>真实目录</dt><dd><code>{binding.cwd}</code></dd><dt>herdr / Agent 会话</dt><dd><code>{binding.session} / {binding.agentSession ?? '未知'}</code></dd><dt>最新观测</dt><dd>{binding.observation ? observations[binding.observation.status] : '未知'} · {date(binding.observation?.observedAt)}（不代表任务结论）</dd><dt>身份依据</dt><dd><code>{binding.fingerprint}</code></dd></dl>{binding.reason && <p className="banner warning">{binding.reason}</p>}<div className="actions">
      {!data.health.storage && <button disabled={disabled} onClick={() => choose(binding, 'emergency-interrupt', '紧急中断', '存储当前不可写，此次紧急中断无法持久化，也不解除执行占用。中断不保证立即停止，请在存储恢复后重新核对实际执行。')}>紧急中断（未持久化）</button>}
      {!binding.confirmed && <button disabled={disabled || !data.health.connected} onClick={() => choose(binding, 'confirm', '确认接入', '请核对下方目录与会话归属，并确认此 Agent 当前没有未完成工作。服务端将重新检查身份与隔离条件。')}>确认接入</button>}
      {binding.mode !== 'automatic' && <button disabled={disabled || !binding.confirmed || !data.health.connected} title={!binding.confirmed ? '请先确认接入与能力' : undefined} onClick={() => choose(binding, 'automatic', '启用自动调度', '自动调度期间，请勿在原生终端替换 Agent 或投递其他独立任务。开展手动工作前先切换模式。')}>自动调度</button>}
      {binding.mode !== 'manual' && <button disabled={disabled} onClick={() => choose(binding, 'manual', '切换手动使用', '暂停后续自动派发；现有执行不会因此取消。请核对占用情况后再使用原生终端。')}>手动使用</button>}
      <button disabled={disabled || (binding.paused && (!binding.confirmed || !data.health.connected))} onClick={() => choose(binding, binding.paused ? 'resume' : 'pause', binding.paused ? '恢复调度' : '暂停调度', binding.paused ? '恢复前服务端将重新核对身份、连接、占用和模式。释放终端控制不会自动完成这一步。' : '暂停后续派发，已经开始的执行继续运行。')}>{binding.paused ? '恢复调度' : '暂停调度'}</button>
    </div></section>)}</div> : <Empty title="接入你的第一个 Agent"><p>已有 Agent 会显示在下方发现列表。先以观察模式接入，确认目录、会话与能力后，再启用自动调度。</p></Empty>}
    {terminal && <div className="standalone-terminal"><div className="heading-row"><h2>实时终端</h2><button onClick={() => openTerminal('')}>关闭终端面板</button></div><Suspense fallback={<p>正在载入终端…</p>}><TerminalPanel key={terminal.id} binding={terminal} csrf={csrf} fresh={fresh && data.health.connected} /></Suspense></div>}
    <section className="discovery"><h2>发现已有 Agent</h2><p className="muted">当前 herdr session：<code>{data.settings.session || '尚未选择'}</code>。接入不会改变目录、清空会话或自动接管输入。</p>{discoveries.length ? discoveries.map(observation => <div key={observation.terminalId} className="discovery-row"><div><strong>{observation.type} · {observation.terminalId}</strong><p><code>{observation.cwd || '目录未知'}</code></p><p className="muted">会话 {observation.agentSession ?? '未知'} · {observations[observation.status]}</p></div><button disabled={disabled || project.archived || !data.health.connected} onClick={() => { void run('/api/v1/bindings', { projectId: project.id, terminalId: observation.terminalId, label: `${observation.type} ${observation.terminalId}`.slice(0, 120) }); }}>以观察模式接入</button></div>) : <p className="muted">没有未接入的 Agent。可刷新观测，或启动 Codex / Claude。</p>}</section>
    {data.starts.filter(record => record.projectId === project.id).length > 0 && <section><h2>启动记录</h2><ul className="timeline">{data.starts.filter(record => record.projectId === project.id).map(record => <li key={record.id}><time>{date(record.createdAt)}</time><span>{record.label} · {record.status === 'started' ? '已启动，等待确认接入' : record.status === 'unknown' ? '启动结果待确认，请核对现有进程' : record.status === 'dismissed' ? '已由人工核对解除' : '已登记启动意图'}</span><span>{record.reason}</span>{record.status === 'unknown' && <button disabled={disabled || !data.health.connected || !data.health.storage} onClick={() => setResolving(record)}>人工核对启动</button>}</li>)}</ul></section>}
    {resolving && <Modal title="人工核对未决启动" description="列表中未发现 Agent 不代表进程已停止。请先在原生 herdr 核对原窗格与进程；若实例仍在，使用观察接入。解除只保存人工核对记录，不会启动、终止或关闭任何实例。" close={() => setResolving(null)}><form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await run(`/api/v1/starts/${resolving.id}/resolve`, { evidence: form.get('evidence'), confirmedStopped: form.get('confirmedStopped') === 'on' })) setResolving(null); }}><dl className="facts"><dt>启动名称</dt><dd>{resolving.label}</dd><dt>原工作目录</dt><dd><code>{resolving.cwd}</code></dd><dt>原终端</dt><dd><code>{resolving.target ?? '未取得终端标识，须人工核对所有相关窗格与进程'}</code></dd></dl><Field label="启动核对证据"><textarea name="evidence" required maxLength={8000} rows={4} /></Field><label className="check"><input name="confirmedStopped" type="checkbox" required />我已在原生 herdr 核对原窗格与进程，确认原启动已停止或从未创建</label><p className="muted">这是一条人工核对声明，不代表服务端证明停止。解除后如需重新启动，请另行发起新的启动操作。</p>{error && <p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" onClick={() => setResolving(null)}>返回</button><Submit pending={pending} disabled={disabled}>保存核对并解除</Submit></div></form></Modal>}
    {start && <Modal title="启动新的 Agent" description="为 Agent 指定独立的真实工作目录。启动与派发任务分开；登录、授权和初始化完成前不会投递任务。" close={() => setStart(false)}><form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await run('/api/v1/starts', { projectId: project.id, type: form.get('type'), cwd: form.get('cwd'), label: form.get('label') })) setStart(false); }}><Field label="Agent 名称"><input name="label" required maxLength={120} placeholder="例如：文档助手" /></Field><Field label="Agent 类型"><select name="type"><option value="codex">Codex</option><option value="claude">Claude</option></select></Field><Field label="独立工作目录" hint="填写已准备好的绝对路径，不能与其他 Agent 目录重叠。"><input name="cwd" required defaultValue={project.root} /></Field>{error && <p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" onClick={() => setStart(false)}>取消</button><Submit pending={pending} disabled={disabled}>确认启动</Submit></div></form></Modal>}
    {action && <Modal title={action.title} description={action.description} close={() => setAction(null)}><form onSubmit={async event => { event.preventDefault(); if (await run(action.name === 'emergency-interrupt' ? `/api/v1/bindings/${action.binding.id}/emergency-interrupt` : `/api/v1/bindings/${action.binding.id}/actions`, action.name === 'emergency-interrupt' ? {} : { action: action.name, expected_revision: action.binding.revision, ...(action.name === 'confirm' ? { evidence: `用户已勾选确认：独立目录 ${action.binding.cwd}；herdr 会话 ${action.binding.session}；Agent 会话 ${action.binding.agentSession ?? '未知'}；无未完成工作；可接受任务并按结果协议提交摘要与产物。` } : {}) })) setAction(null); }}><dl className="facts"><dt>Agent</dt><dd>{action.binding.label}</dd><dt>工作目录</dt><dd><code>{action.binding.cwd}</code></dd><dt>herdr / Agent 会话</dt><dd><code>{action.binding.session} / {action.binding.agentSession ?? '未知'}</code></dd></dl>{action.name === 'confirm' && <><label className="check"><input type="checkbox" required />我已核对目录、项目及独立会话归属，且当前没有未完成工作</label><label className="check"><input type="checkbox" required />此 Agent 可接受任务，并能按约定结果协议提交摘要及产物</label><p className="muted">同一系统用户下的目录隔离不构成操作系统权限隔离。共享端口、数据库等资源仍需自行安排。</p></>}{error && <p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" onClick={() => setAction(null)}>返回</button><Submit pending={pending} disabled={disabled}>{action.title.startsWith('确认') ? action.title : `确认${action.title}`}</Submit></div></form></Modal>}
  </>;
}
