import { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { Folder, ListTodo, Monitor, Pause, Play, Plus, Settings2, Workflow } from 'lucide-react';
import { useConsole } from './api.js';
import { Agents } from './Agents.js';
import { TaskActionDialog, TaskDetail, TaskForm, TaskList, type TaskAction } from './Tasks.js';
import { date, Empty, Field, Modal, Submit } from './ui.js';
import type { Task } from '@meteor-flow/contracts';

export function App() {
  const { auth, snapshot, sessions, run, pending, notice, eventWarning, setNotice, stale, csrf } = useConsole();
  const [params, setParams] = useSearchParams();
  const [modal, setModal] = useState<'project' | 'session' | 'settings' | 'task' | 'archive-project' | null>(null);
  const [editTask, setEditTask] = useState<Task | undefined>();
  const [taskAction, setTaskAction] = useState<TaskAction | null>(null);
  const setParam = (key: string, value: string) => setParams(current => { const next = new URLSearchParams(current); if (value) next.set(key, value); else next.delete(key); return next; });
  const open = (value: typeof modal) => { setNotice(null); setModal(value); };
  if (auth.isPending) return <main className="gate"><Workflow size={32} /><h1>Meteor Flow</h1><p role="status">正在连接本地控制台…</p></main>;
  if (auth.isError || !auth.data?.authenticated) return <main className="gate"><Workflow size={32} /><h1>连接你的本地控制台</h1><p>请从 Meteor Flow 启动终端打开带一次性凭证的链接，以访问本机任务与终端。</p>{auth.isError && <p className="form-error" role="alert">{auth.error.message}</p>}<button onClick={() => { location.reload(); }}>重新检查连接</button></main>;
  const data = snapshot.data;
  if (!data) return <main className="gate"><h1>Meteor Flow</h1><p role="status">{snapshot.isError ? '无法读取本地状态，请确认服务仍在运行。' : '正在读取任务与 Agent…'}</p><button onClick={() => { void snapshot.refetch(); }}>重新读取状态</button></main>;
  const projects = data.projects;
  const defaultProject = projects.find(item => !item.archived) ?? projects[0];
  const project = projects.find(item => item.id === params.get('project')) ?? defaultProject;
  const view = params.get('view') === 'agents' ? 'agents' : 'tasks';
  const selectedTask = data.tasks.find(task => task.id === params.get('task') && task.projectId === project?.id);
  const disabled = stale || pending;
  const error = notice?.error ? notice.text : undefined;
  const chooseProject = (id: string) => setParams(current => { const next = new URLSearchParams(current); next.set('project', id); next.delete('task'); next.delete('terminal'); return next; });
  return <div className="app-shell"><a className="skip-link" href="#main">跳到主要内容</a><aside className="sidebar"><div className="brand"><Workflow size={24} /><strong>Meteor Flow</strong></div><p className="sidebar-caption">本地 Agent 控制台</p>
    <div className="sidebar-section"><label htmlFor="project-switch">当前项目</label><select id="project-switch" value={project?.id ?? ''} onChange={event => chooseProject(event.target.value)}>{!projects.length && <option value="">尚无项目</option>}{projects.map(item => <option key={item.id} value={item.id}>{item.name}{item.archived ? '（已归档）' : ''}</option>)}</select><button className="subtle" disabled={disabled} onClick={() => open('project')}><Plus size={15} />创建项目</button></div>
    <nav aria-label="主导航"><button className={view === 'tasks' ? 'nav-item selected' : 'nav-item'} aria-current={view === 'tasks' ? 'page' : undefined} onClick={() => setParam('view', '')}><ListTodo size={19} />任务</button><button className={view === 'agents' ? 'nav-item selected' : 'nav-item'} aria-current={view === 'agents' ? 'page' : undefined} onClick={() => setParam('view', 'agents')}><Monitor size={19} />Agent</button></nav>
    <div className="sidebar-session"><span className="sidebar-caption">HERDR SESSION</span><strong>{data.settings.session || '尚未选择'}</strong><button disabled={disabled} onClick={() => open('session')}>选择 / 切换会话</button><small>{data.health.version ? `herdr ${data.health.version}` : '版本尚未核实'}</small></div>
    {project && <div className="sidebar-project"><Folder size={15} /><code>{project.root}</code><button className="text-button" disabled={disabled || project.archived} onClick={() => open('archive-project')}>归档当前项目</button></div>}
  </aside><div className="workspace"><header className="topbar"><div className="connection"><span className={`connection-dot ${stale || !data.health.connected ? 'offline' : ''}`} /><strong>{stale ? '状态已过期' : data.health.connected ? '本地连接正常' : 'herdr 未连接'}</strong><small>最后观测 {date(data.health.lastObservation)}</small></div><div className="actions"><span className="muted">并行上限 {data.settings.concurrency}</span><button disabled={disabled} onClick={() => open('settings')}><Settings2 size={16} />调度设置</button><button disabled={disabled} onClick={() => open('settings')}>{data.settings.paused ? <Play size={16} /> : <Pause size={16} />}{data.settings.paused ? '全局已暂停' : '暂停调度'}</button></div></header>
    <main id="main" tabIndex={-1}>
      {eventWarning && <p className="banner warning" role="status">{eventWarning}</p>}
      {stale && <div className="banner danger" role="alert">无法读取最新状态，已保留上次快照并暂停页面操作。<button onClick={() => { void snapshot.refetch(); }}>重新读取状态</button></div>}
      {!data.health.storage && <div className="banner danger" role="alert"><span>本地存储不可写，调度已停止。{data.health.error}</span><button disabled={disabled} onClick={() => { void run('/api/v1/storage/recover', {}); }}>恢复存储</button></div>}
      {data.health.error && data.health.storage && <p className="banner warning">{data.health.error}</p>}
      {data.settings.paused && <p className="banner neutral">全局调度已暂停。已开始的执行继续运行；在调度设置中核对后恢复。</p>}
      {project?.archived && <p className="banner neutral">此项目已归档，历史任务与结果仍可查看。新任务不会派发。</p>}
      {notice && <div className={`banner ${notice.error ? 'danger' : 'success'}`} role={notice.error ? 'alert' : 'status'}><span>{notice.text}</span><button className="text-button" onClick={() => setNotice(null)}>关闭提示</button></div>}
      {!project ? <Empty title="建立你的第一个项目"><p>按会话 → 项目 → Agent → 任务开始。项目用于归属工作目录、输入与执行结果。</p><div className="actions"><button disabled={disabled} onClick={() => open('session')}>选择 herdr 会话</button><button className="primary" disabled={disabled} onClick={() => open('project')}>创建项目</button></div></Empty> : view === 'agents' ? <Agents key={project.id} data={data} project={project} run={run} disabled={disabled} fresh={!stale} pending={pending} csrf={csrf} error={error} terminalId={params.get('terminal') ?? ''} openTerminal={id => setParam('terminal', id)} /> : <><TaskList data={data} project={project} search={params.get('q') ?? ''} phase={params.get('phase') ?? ''} archived={params.get('archived') === '1'} setFilter={setParam} selectTask={id => { setParam('task', id); if (selectedTask?.id === id) { const heading = document.getElementById('task-detail-heading'); heading?.focus({ preventScroll: true }); heading?.scrollIntoView({ block: 'start' }); } }} create={() => { setEditTask(undefined); open('task'); }} disabled={disabled || project.archived} />{selectedTask && <TaskDetail key={selectedTask.id} data={data} task={selectedTask} csrf={csrf} disabled={disabled} fresh={!stale} close={() => { const origin = document.getElementById(`task-select-${selectedTask.id}`); setParam('task', ''); requestAnimationFrame(() => { (origin?.isConnected ? origin : document.getElementById('main'))?.focus(); }); }} edit={() => { setEditTask(selectedTask); open('task'); }} action={value => { setNotice(null); setTaskAction(value); }} />}</>}
    </main><footer>任务由本地服务管理。关闭此页面不会取消执行。</footer></div>
    {modal === 'project' && <Modal title="创建项目" description="项目关联一个真实工作目录；Agent 仍需各自具备独立目录与会话。" close={() => setModal(null)}><form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await run('/api/v1/projects', { name: form.get('name'), root: form.get('root') })) setModal(null); }}><Field label="项目名称"><input required name="name" maxLength={120} placeholder="例如：检索实验" /></Field><Field label="项目根目录"><input required name="root" maxLength={4096} placeholder="/Users/you/projects/example" /></Field>{error && <p role="alert" className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" onClick={() => setModal(null)}>取消</button><Submit pending={pending} disabled={stale}>创建项目</Submit></div></form></Modal>}
    {modal === 'session' && <Modal title="选择 herdr 会话" description="第一版只管理一个本地 herdr session。切换前必须处理当前执行与绑定限制，服务端会核对是否允许。" close={() => setModal(null)}><form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await run('/api/v1/session', { session: form.get('session') })) setModal(null); }}><Field label="herdr session"><select name="session" required defaultValue={data.settings.session || ''}><option disabled value="">选择已发现的会话</option>{sessions.data?.sessions.map(session => <option key={session.name} value={session.name}>{session.name} · {session.socketPath}</option>)}</select></Field>{sessions.isError ? <p className="form-error" role="alert">会话列表读取失败。<button type="button" onClick={() => { void sessions.refetch(); }}>重新读取会话</button></p> : !sessions.data?.sessions.length && <p className="muted">尚未发现会话。请先启动 herdr，再重新读取会话列表。</p>}{error && <p role="alert" className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" onClick={() => { void sessions.refetch(); }}>刷新会话</button><Submit pending={pending} disabled={stale || sessions.isError || !sessions.data?.sessions.length}>确认选择</Submit></div></form></Modal>}
    {modal === 'settings' && <Modal title="全局调度设置" description="暂停只阻止新的派发。降低并行上限不会中断已开始的执行；恢复时重新检查各 Agent 当前事实。" close={() => setModal(null)}><form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); if (await run('/api/v1/settings', { paused: form.get('paused') === 'on', concurrency: Number(form.get('concurrency')) })) setModal(null); }}><label className="check"><input type="checkbox" name="paused" defaultChecked={data.settings.paused} />暂停全局自动调度</label><Field label="本机并行任务上限（1–8）"><input type="number" name="concurrency" required min={1} max={8} defaultValue={data.settings.concurrency} /></Field>{error && <p role="alert" className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" onClick={() => setModal(null)}>取消</button><Submit pending={pending} disabled={stale}>保存调度设置</Submit></div></form></Modal>}
    {modal === 'archive-project' && project && <Modal title="归档项目" description={`归档「${project.name}」后将停止新任务派发，并保留历史入口。历史任务与依赖不会删除；归档不取消已开始的执行。`} close={() => setModal(null)}>{error && <p role="alert" className="form-error">{error}</p>}<div className="dialog-actions"><button onClick={() => setModal(null)}>返回</button><button disabled={disabled} onClick={async () => { if (await run(`/api/v1/projects/${project.id}/archive`, {})) setModal(null); }}>确认归档项目</button></div></Modal>}
    {modal === 'task' && project && <TaskForm data={data} project={project} task={editTask} run={run} pending={pending} disabled={stale} error={error} close={() => setModal(null)} />}
    {taskAction && <TaskActionDialog value={taskAction} run={run} pending={pending} disabled={stale} error={error} close={() => setTaskAction(null)} />}
  </div>;
}
